"""empty message

Revision ID: d658a1fa245c
Revises: 
Create Date: 2020-11-02 13:11:32.556214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd658a1fa245c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('destination', sa.String(), nullable=True),
    sa.Column('claimed', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    # ### end Alembic commands ###
